## Tiba tiba QUISZ

In [2]:
def tambah(a, b):
    return a + b

def kurang(a, b):
    return a - b

def kali(a, b):
    return a * b

def bagi(a, b):
    return a / b

def pangkat(a, b):
    return a ** b

while True:
    try:
        angka1 = int(input("Masukkan angka pertama: "))
        break
    except ValueError:
        print("Input salah")

operator = input("Masukkan pilihan operator: ")

while True:
    try:
        angka2 = int(input("Masukkan angka kedua: "))
        break
    except ValueError:
        print("Input salah")

if operator == '+':
    print(angka1, '+', angka2, '=', tambah(angka1, angka2))
elif operator == '-':
    print(angka1, '-', angka2, '=', kurang(angka1, angka2))
elif operator == 'x':
    print(angka1, 'x', angka2, '=', kali(angka1, angka2))
elif operator == ':':
    print(angka1, ':', angka2, '=', bagi(angka1, angka2))
elif operator == '^':
    print(angka1, '^', angka2, '=', pangkat(angka1, angka2))
else:
    print("Operator", operator, "tidak ditemukan")



Masukkan angka pertama:  asd


Input salah


Masukkan angka pertama:  qwe


Input salah


Masukkan angka pertama:  12
Masukkan pilihan operator:  x
Masukkan angka kedua:  13


12 x 13 = 156


In [6]:
c = '12'
x = 'lalala'
# c.isnumeric()
x.isnumeric()

False

In [7]:
pip install numpy

In [47]:

## One dimentional array
import numpy as np
c = np.array([1,2,3,4])
c[1]
c[1:4]
# print(c.shape)


array([2, 3, 4])

In [22]:
## Two dimentional array
list_of_list = [[1,2,3], [2,2,4], [3,4,5]]
array_1 = np.array(list_of_list)
print('Shape: ', array_1.shape)

np.array(list_of_list)
## axis 0 : 123, 224, 345(bawah)
## axis 1 : (samping)

## Shape itu axis0, axis 1

Shape:  (3, 3)


array([[1, 2, 3],
       [2, 2, 4],
       [3, 4, 5]])

In [24]:
## Creating Array

## np.zeros
np.zeros(89)
np.zeros([12,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [27]:
np.ones([2,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
np.empty([3,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [29]:
np.empty(6)

array([0., 0., 0., 0., 0., 0.])

In [33]:
np.arange(0,13,3)

array([ 0,  3,  6,  9, 12])

In [43]:
mauapend = np.arange(0,10)
print(mauapend)

apend1 = np.append(mauapend, [1,2,3])
print(apend1)

apend2 = np.delete(apend1, 9)
print(apend2.reshape(3,4))


[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9 1 2 3]
[[0 1 2 3]
 [4 5 6 7]
 [8 1 2 3]]


In [52]:
# np expand dims
array7 = np.arange(3,10)
print(array7)
array8 = np.expand_dims(array7, axis=0)
print(array8)

[3 4 5 6 7 8 9]
[[3 4 5 6 7 8 9]]


In [58]:
## array bisa dilakukan operasi matematika
# array7 = np.array([3,10])
array7*2
print(array7)

[ 3 10]


In [60]:
# Filtering Array
array7 = np.arange(3,10)
print(array7[array7>5])
print(array7[array7<5])

[6 7 8 9]
[3 4]


In [ ]:
## QUIZ 2

In [69]:
def jam_pasir(n):
    for i in range(n):
        for j in range(i):
            print(' ', end='')
        for j in range(n-1):
            print('* ', end='')
        print()
n = int(input("Masukkan angka : "))       
jam_pasir(n)

Masukkan angka :  5


* * * * 
 * * * * 
  * * * * 
   * * * * 
    * * * * 


In [71]:
# STACK
# VSTACK, HSTACK
array14 = np.arange(3,8)
array15 = np.arange(7,12)
print("Stack Vertical")
print(np.vstack([array14,array15]))
print('Stack Horizontal')
print(np.hstack([array14,array15]))

Stack Vertical
[[ 3  4  5  6  7]
 [ 7  8  9 10 11]]
Stack Horizontal
[ 3  4  5  6  7  7  8  9 10 11]


In [74]:
#SPLIT
#VSPLIT dan HSPLIT
array14 = np.arange(3,8)
array15 = np.arange(7,12)
print("Split Vertical")
print(np.vsplit([array14,2]))
print('Split Horizontal')
print(np.hsplit([array14,2]))

Split Vertical
Split Horizontal


TypeError: _hvdsplit_dispatcher() missing 1 required positional argument: 'indices_or_sections'

In [77]:
# TRANSPOSING 
arrayc = np.array([[1,2,3], [3,4,5]])
print(arrayc)
print(arrayc.shape)

[[1 2 3]
 [3 4 5]]
(2, 3)


In [80]:
print(arrayc.T)
print(arrayc.T.shape)

[[1 3]
 [2 4]
 [3 5]]
(3, 2)


In [92]:
def bil_prima(awal, akhir):
    prima = []
    for i in range(awal, akhir + 1):
        if i > 1:
            for j in range(2, i):
                if (i % j) == 0:
                    break
            else:
                prima.append(i)
    return prima
awal = int(input("Masukkan nilai awal : "))
akhir = int(input("Masukkan nilai akhir : "))
print(bil_prima(awal,akhir))

Masukkan nilai awal :  0
Masukkan nilai akhir :  22


[2, 3, 5, 7, 11, 13, 17, 19]


In [94]:
awal = int(input("Masukkan angka : "))
akhir = int(input("Masukkan angka : "))

for i in range(awal, akhir + 1):
    if i > 1 : 
        for j in range(2,i):
            if(i%j)==0:
                break
        else:
            print(i)
        

Masukkan angka :  10
Masukkan angka :  30


11
13
17
19
23
29


In [95]:
n=int(input('Mau mulai dari berapa bintang nih ? '))
t=0

if n%2==0:
   t=n-1
else:
   t=n

for i in range(0,t):
   if (t-2*i)>0: 
      print(' '*i+'*'*(t-2*i))
   else:
      k=t-i-1
      print(' '*k+'*'*(t-2*k))

Mau mulai dari berapa bintang nih ?  8


*******
 *****
  ***
   *
  ***
 *****
*******


## Numpy dari video kode.id

In [1]:
import numpy as np
np.__version__

'1.21.5'

## Python LIST

In [7]:
gpas_as_list = [4.0, 3.2, 3.5]


In [8]:
gpas_as_list.append(4.0)
gpas_as_list

[4.0, 3.2, 3.5, 4.0]

In [9]:
gpas_as_list.insert(2, 'Belum ada')
gpas_as_list

[4.0, 3.2, 'Belum ada', 3.5, 4.0]

In [10]:
gpas_as_list.pop()
gpas_as_list

[4.0, 3.2, 'Belum ada', 3.5]

In [11]:
gpas_as_list.pop(2)
gpas_as_list

[4.0, 3.2, 3.5]

## Array NUMPY

In [13]:
gpas = np.array(gpas_as_list)

In [16]:
gpas.dtype

dtype('float64')

In [17]:
gpas.size

3

In [29]:
gpas

array([4.  , 3.2 , 3.5 , 2.79, 2.79])

In [32]:
gpas = np.array(gpas_as_list)
gpas

array([4.  , 3.2 , 3.5 , 2.79, 2.79])

In [33]:
gpas = np.array(gpas_as_list.pop(4))

In [34]:
gpas

array(2.79)

In [36]:
gpas = np.array(gpas_as_list)

In [37]:
gpas

array([4.  , 3.2 , 3.5 , 2.79])

## Array Multi Diomensi

In [39]:
student_gpas = np.array([
    [4.0, 3.45, 4, 2.6],
    [4.0, 3.32, 1.4, 3.6],
    [4, 3.5, 3.9, 2.6],
    [4.0, 3.55, 4, 3.83]
], np.float16) 

student_gpas

array([[4.  , 3.45, 4.  , 2.6 ],
       [4.  , 3.32, 1.4 , 3.6 ],
       [4.  , 3.5 , 3.9 , 2.6 ],
       [4.  , 3.55, 4.  , 3.83]], dtype=float16)

In [40]:
student_gpas.ndim

2

In [42]:
student_gpas.shape

(4, 4)

In [43]:
student_gpas[3]

array([4.  , 3.55, 4.  , 3.83], dtype=float16)

In [44]:
student_gpas[2][3] ## Mengamil nilai IPK Student ke 3 dan IPK ke 4

2.6